site_name: "Projekt: Matrix na PWr"
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    # - navigation.sections
    - navigation.expand
  palette: 
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - awesome-pages
markdown_extensions:
    - toc:
        permalink: True
        baselevel: 3
        separator: "_"
    - pymdownx.tasklist:
        custom_checkbox: true
    - tables
    - attr_list
    - footnotes
